#-------------------------#
#                         #
#   NAME:     APARKOUR    #
#   AUTHOR:   DavidML16   #
#                         #
#-------------------------#


# CHECK UPDATES
CheckUpdates: true


# LANGUAGE OF THE PLUGIN
# AVAILABLES BY DEFAULT: EN, ES
Language: EN


# DATABASE DETAILS
MySQL:
    Enabled: false
    Host: localhost
    Port: 3306
    User: root
    Password: example
    Database: aparkour


# PLAYER GAMEMODE WHILE PLAYING IN PARKOUR
ParkourGamemode: 'ADVENTURE'


# ENABLE JOIN PARKOUR BY GUI, AND COMMAND /PARKOUR PLAY
JoinParkourByGUI: true


# ENABLE PLAYER RANK IN HOLOGRAMS
UseVaultInHolograms: false


#-----------------------------------------------------------#
#   COMMAND BLOCKER TYPES:                                  #
#       - "blacklist": block all commands in the list       #
#       - "whitelist": only allow commands in the list      #
#-----------------------------------------------------------#
CommandBlocker:
    Type: "whitelist"
    Commands:
        - 'aparkour'
        - 'apk'
        - 'pk'


# ENABLE HOLOGRAMS, YOU NEED DEPENDENCIES
# RELOAD INTERVAL OF TOP HOLOGRAM AND TOP GUI
Hologram:
    Enabled: true
    ReloadInterval: 120


# RETURN TO SPAWN ON PARKOUR END
TpToParkourSpawn:
    Enabled: false


# KICK FROM PARKOUR ON FAIL
KickParkourOnFail:
    Enabled: true


# LAUNCH FIREWORK ON PARKOUR END
Firework:
    Enabled: true


# RETURN TO SPAWN WHEN PLAYER FLY
ReturnOnFly:
    Enabled: true


# RETURN TO SPAWN/CHECKPOINT IF YOU FALL OF SPECIFIED BLOCKS
ReturnOnFall:
    Enabled: false
    BlocksDistance: 5


# ACTION BAR TIMER WHILE PLAYING PARKOUR
ActionBarTimer:
    Enabled: true


# PARKOUR ITEMS | IF YOU HAVE DISABLED, THE INVENTORY DON'T CLEAR
Items:
    Enabled: true
    Restart:
        ID: 166
        Name: '&4&lRestart'
        Lore: '&7Return to the start of the course to start again!'
    Checkpoint:
        ID: 148
        Name: '&a&lCheckpoint'
        Lore: '&7Return to your last checkpoint of the course!'


# SOUNDS OF PARKOUR EVENTS
Sounds:
    ParkourStart:
        Enabled: true
        Sound: CLICK
        Volume: 10
        Pitch: 2
    ParkourEnd:
        Enabled: true
        Sound: CLICK
        Volume: 10
        Pitch: 2
    Fly:
        Enabled: true
        Sound: BAT_TAKEOFF
        Volume: 10
        Pitch: 2
    Fall:
        Enabled: true
        Sound: BAT_TAKEOFF
        Volume: 10
        Pitch: 2
    Return:
        Enabled: true
        Sound: BAT_TAKEOFF
        Volume: 10
        Pitch: 2