#-------------------------#
#                         #
#   NAME:     APARKOUR    #
#   AUTHOR:   DavidML16   #
#                         #
#-------------------------#


Language: EN


MySQL:
    Enabled: false
    Host: localhost
    Port: 3306
    User: root
    Password: example
    Database: aparkour


ParkourGamemode: 'ADVENTURE'


BlockedCommands:
    - 'home'
    - 'sethome'
    - 'spawn'


TpToParkourSpawn:
    Enabled: false


Firework:
    Enabled: true


ReturnOnFly:
    Enabled: true


ReturnOnFall:
    Enabled: false
    BlocksDistance: 5


ActionBarTimer:
    Enabled: true


Items:
    Enabled: true
    Restart:
        ID: 166
        Name: '&4&lRestart'
        Lore: '&7Return to the start of the course to start again!'
    Checkpoint:
        ID: 148
        Name: '&a&lCheckpoint'
        Lore: '&7Return to your last checkpoint of the course!'


Hologram:
    Enabled: true


Tasks:
    ReloadInterval: 120


Sounds:
    ParkourStart:
        Enabled: true
        Sound: CLICK
        Volume: 10
        Pitch: 2
    ParkourEnd:
        Enabled: true
        Sound: CLICK
        Volume: 10
        Pitch: 2
    Fly:
        Enabled: true
        Sound: BAT_TAKEOFF
        Volume: 10
        Pitch: 2
    Fall:
        Enabled: true
        Sound: BAT_TAKEOFF
        Volume: 10
        Pitch: 2
    Return:
        Enabled: true
        Sound: BAT_TAKEOFF
        Volume: 10
        Pitch: 2