name: AParkour
version: ${project.version}
author: DavidML16
main: me.davidml16.aparkour.Main
load: POSTWORLD
softdepend: [HolographicDisplays, ProtocolLib, PlaceholderAPI]
commands:
    aparkour:
        description: Use this to see all commands.
        aliases: [apk,pk]