name: AParkour
version: ${project.version}
author: DavidML16
main: me.davidml16.aparkour.Main
load: POSTWORLD
depend: [HolographicDisplays, ProtocolLib, HideItem]
softdepend: [PlaceholderAPI, Vault]
commands:
    aparkour:
        description: Use this to see all commands.
        aliases: [apk,pk]